<a href="https://colab.research.google.com/github/DhruvMazumdar1110/Weather-Data-Preprocessing/blob/main/Weather_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE LIBRARIES


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

IMPORTING THE DATASET


In [ ]:
dataset = pd.read_csv('weather_data.csv')
X= dataset.iloc[: , [0,1,3,4,5] ].values
y= dataset.iloc[: , 2].values

In [ ]:
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['New York' '2024-04-14 08:30:09' 62.20188442965286 3.9875580386419296
  0.4039090307166959]
 ['Chicago' '2024-05-12 20:10:43' 63.7032451997448 4.294324709830695
  6.326035560339499]
 ['New York' '2024-04-16 16:11:52' 43.80458378329061 1.8832923531385992
  15.363828427249876]]


In [ ]:
print(y)

[10.68300109  8.73413978 11.63243631 ... 15.66446487 18.99999414
 10.72535108]


HANDLING MISSING DATA

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])
print(X)

[['San Diego' '2024-01-14 21:12:46' 41.19575356694448 4.02011871570867
  8.233540246873023]
 ['San Diego' '2024-05-17 15:22:10' 58.31910739552024 9.111623448229375
  27.71516125689249]
 ['San Diego' '2024-05-11 09:30:59' 38.82017526915946 4.607511377146035
  28.732951288236187]
 ...
 ['New York' '2024-04-14 08:30:09' 62.20188442965286 3.9875580386419296
  0.4039090307166959]
 ['Chicago' '2024-05-12 20:10:43' 63.7032451997448 4.294324709830695
  6.326035560339499]
 ['New York' '2024-04-16 16:11:52' 43.80458378329061 1.8832923531385992
  15.363828427249876]]


ENCODING DATA BY COLUMN TRANSFER

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 41.19575356694448 4.02011871570867 8.233540246873023]
 [0.0 0.0 0.0 ... 58.31910739552024 9.111623448229375 27.71516125689249]
 [0.0 0.0 0.0 ... 38.82017526915946 4.607511377146035 28.732951288236187]
 ...
 [0.0 0.0 0.0 ... 62.20188442965286 3.9875580386419296 0.4039090307166959]
 [1.0 0.0 0.0 ... 63.7032451997448 4.294324709830695 6.326035560339499]
 [0.0 0.0 0.0 ... 43.80458378329061 1.8832923531385992 15.363828427249876]]


SPLITTING THE DATASET INTO TRAINING AND TEST SET


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_test)

[[0.0 1.0 0.0 ... 58.17244349125963 3.6859997050174655 7.412617198139213]
 [0.0 0.0 0.0 ... 72.13247860088072 5.600919990094316 12.295135537222407]
 [0.0 0.0 0.0 ... 78.94520496126287 11.383102447141416 18.11876142341646]
 ...
 [0.0 0.0 0.0 ... 81.2558198685081 1.0821356481564626 21.26671932550913]
 [0.0 0.0 1.0 ... 63.93210119410432 7.107507204412746 15.172276612959504]
 [0.0 0.0 0.0 ... 83.186365722186 4.432723603217546 2.9681138979312727]]


In [ ]:
print(y_train)

[13.30673517  1.65457701 29.25607097 ... -0.81428762 21.84013754
 24.22000906]


In [ ]:
print(y_test)

[14.00262063 32.70461618 20.0566492  ... -8.97270918 22.93430013
 23.49722793]


STANDARDIZATION

In [ ]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 11:] = sta.fit_transform(X_train[:, 11:])
X_test[:, 11:] = sta.transform(X_test[:, 11:])

In [ ]:
print(X_train[:, 11:])

[[-0.7408501311736168 1.1514500050187195 0.5651657428482892]
 [1.532369419786475 1.0524729494061305 -1.6106053480395277]
 [0.5968289852116786 1.1692446081846386 -1.1918733617430788]
 ...
 [1.13431148671869 -0.1362010624988719 -0.9165429657956747]
 [-0.30141642577624833 -0.5844664862516075 0.6519305569244803]
 [-1.3273227767063605 0.0003309447376233136 0.8883799108273236]]


In [ ]:
print(X_test[:, 11:])

[[-0.10626099917017652 -0.48371596998601085 -0.8759267390839591]
 [0.6996308804222644 0.1659819599012277 -0.31236642481994925]
 [1.092919350587607 2.1277722244098327 0.35982038670891575]
 ...
 [1.2263076820632797 -1.3671601011251235 0.7231706132492507]
 [0.2262353975441564 0.677139840448711 0.019725011651491167]
 [1.3377551973770219 -0.23036601352113825 -1.3889295590760165]]


In [2]:
import pandas as pd

# Convert X (features) back to a DataFrame
# Note: Column names are lost after OneHotEncoder and StandardScaler. Generic names are used.
# If you need original column names, you'd need to store them before encoding/scaling.
X_df = pd.DataFrame(X)
X_df.to_csv('cleansed_features.csv', index=False)
print("Cleansed features saved to 'cleansed_features.csv'")

# Convert y (target) back to a DataFrame
y_df = pd.DataFrame(y, columns=['target_variable'])
y_df.to_csv('cleansed_target.csv', index=False)
print("Cleansed target saved to 'cleansed_target.csv'")

NameError: name 'X' is not defined